---
name: codecov
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  pytest:
    env:
      python-version: "3.11"
      poetry-version: "1.8.3"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python-version }}
      - name: Set up Poetry ${{ env.poetry-version }}
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ env.poetry-version }}
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Run tests and collect coverage
        run: poetry run pytest --cov=. --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
